### PR TITLE
Re-enable RETURNING support

### PR DESCRIPTION
**Pull request by knz**

### CODE REVIEW

**Comment by knz** [comment]
@rafiss can you take this PR over thanks

**Comment by rafiss** [comment]
Thanks, this is good timing. I actually just started doing this myself.

**Comment by rafiss** [comment]
Will hold off on doing this until we find a third-party contractor to work on Sequelize items.

**Comment by papb** [comment]
Hello! I investigated this. I'd like to point out that since [Sequelize v6](https://github.com/sequelize/sequelize/releases/tag/v6.1.0), upsert is implemented in postgres with `ON CONFLICT DO UPDATE`, so your workaround is no longer needed! :grin:

Here is a mini example that uses Sequelize v6 directly (instead of `sequelize-cockroachdb`) to connect to CockroachDB and execute an upsert (even with `returning: true` set):

```js
const { Sequelize, DataTypes } = require('sequelize');
const sequelize = new Sequelize('postgres://some_user@localhost:26257/test'); // CockroachDB

const log = arg => console.log(JSON.stringify(arg, undefined, 4));

(async () => {
	const User = sequelize.define('user', { name: DataTypes.STRING }, { timestamps: false });
	await sequelize.sync({ force: true });
	const { id } = await User.create({ name: 'Someone' });
	log(await User.upsert({ id, name: 'Another Name' }, { returning: true }));
	await sequelize.close();
})();
```

The executed query:

```sql
INSERT INTO "users" ("id","name")
VALUES ($1,$2)
ON CONFLICT ("id") DO UPDATE SET "id"=EXCLUDED."id","name"=EXCLUDED."name"
RETURNING "id","name";
```

**Comment by papb** [comment]
If you really need compatibility with Sequelize v5, then indeed a workaround like you currently have will be needed. I think the safest way to code this workaround is by copying the relevant v6 code ([this part in particular](https://github.com/sequelize/sequelize/blob/a329bb76e9efa1f4c0f24f8be7c7ddda0a464ae8/lib/dialects/abstract/query-generator.js#L290-L293)) in order to ensure all options are supported (for example, your current workaround does not account for the `upsertKeys` option).

However, with that said, my advice would be to encourage your users to upgrade to v6 instead of trying to ensure compatibility with v5. If you have customers using v5 and having trouble upgrading to v6, I believe it is better to spend some time helping them upgrade than spending some time creating workarounds here. [Upgrading from v5 to v6 shouldn't be too hard](https://sequelize.org/master/manual/upgrade-to-v6.html).

Also, please note that Sequelize v3 and v4 [are no longer supported](https://github.com/sequelize/sequelize/blob/master/SECURITY.md#supported-versions) (not even for security patches).

**Pull request closed without merging**
